name: Deploy to AWS EC2 via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest # Github-hosted Runner
    steps:
      - name: Checkout code
        run: echo "checkout code"
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        run: echo "deploy via SSH"
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/scheduler
            git pull origin main
